### ISSUE TITLE
Theory of Constraints

### ISSUE THREAD

**Issue by g-asantos** [jmfantin2/ftbok#1]
Eu vi o video da Teoria das Restrições, e eu sai com algumas perguntas, talvez óbvias mas não custa perguntar hahah
1.  Qual aplicação prática da Teoria das Restrições?  Qual é o equivalente real de "chacoalhar a garrafa e colocar um canudo para sugar o ar de dentro"?
2. Está dentro da categoria de gestão de pessoas mas seria possível aplicar essa teoria na sua vida individual, com foco em crescimento?

**Comment by Jozgon** [comment]
1- Imagino que a teoria das restrições tem a ver com domínio da técnica, de forma que não é necessário agir impulsivamente em qualquer contexto de vida. Podemos ouvir de uma pessoa com mais experiência ou ao menos com outra perspectiva para tentar resolver quaisquer problemas. Problemas são melhores pensados em conjunto. Acredito que isso que queira dizer essa teoria.

2- Sim, eu acho que possivelmente sim. Acho que não há crescimento pessoal sem convívio pessoal.

**Comment by audreybehenck** [comment]
Segundo a minha interpretação, existem várias formas de obter sucesso no nosso objetivo final.
Porém, devemos pensar e analisar o que podemos fazer pra que esse objetivo seja concluído de uma forma mais eficaz.
Não estou falando que a forma mais eficaz seja esvaziar mais rápido a garrafa, mas que devemos pensar o que podemos fazer pra que obtenhamos um resultado final bom, de uma forma mais eficaz.

**Comment by jmfantin2** [comment]
1. O equivalente real de virar a garrafa e soprar pro ar ir pro lugar certo sou eu trabalhando 12 horas no onboarding de vocês sem ninguém me obrigar (porque eu sei que vai fazer toda a diferença pra água descer e no futuro vai me estressar menos) hehehe
2. Com certeza. A lógica é entender que movimento e esforço são duas coisas muito diferentes.

2.1
Caso A - deixa a água descer sozinha (e ela que se f#%@): pouco movimento e um monte de esforço.
Caso B - dá uma dançada e direciona o turbilhão: movimento e esforço equilibrados.
Caso C - cria um canal sem atrito pro ar passar: movimento ótimo e esforço significativo apenas no momento 0.

O IMPORTANTE PRO DESENVOLVIMENTO DE VOCÊS:
Se estiver se esforçando demais para se movimentar pouco, alguma coisa está errada. A suspeita do mercado inteiro é que tem a hora de reconhecer que é preciso receber ajuda. (e **aqui a dúvida é celebrada**)
