### ISSUE TITLE
Review do Curso de Java

### ISSUE THREAD

**Issue by cali0p3** [jmfantin2/ftbok#10]
Olá colegas!

Eu upei os testes do Curso de Java.
Acredito que tenha feito certo.

Se alguém puder dar um olhadinha, ficarei muito agradecida!

Segue link:
https://github.com/Robertta-dev/CursoJava

**Comment by jmfantin2** [comment]
Show!! Só scrolla até alí embaixo e troca a visibilidade pra público https://github.com/Robertta-dev/CursoJava/settings ;)

**Comment by jmfantin2** [comment]
Olhadinha dada. Será que não faltou um `push`?

**Comment by cali0p3** [comment]
Deu ruim. Não consigo mais abrir os arquivos no eclipse :_(

**Comment by jmfantin2** [comment]
aplique exorcismo

**Comment by cali0p3** [comment]
Em mim né kkkk

**Comment by cali0p3** [comment]
Aparece o seguinte erro:

The Class File Viewer cannot handle the given input ('org.eclipse.ui.ide.FileStoreEditorInput').

**Comment by eneri-jr** [comment]
Bom dia,

Pelo que li sobre este erro parece que tu esta tentando abrir os arquivos .class no eclipse da pasta bin e na verdade os arquivos que o eclipse trabalha são os .java que estão na pasta src do projeto.
(Obs.: os arquivos .class são arquivos binários e os arquivos .Java são o código fonte)

Tenta abrir os arquivoa de extensão .java no eclipse e qualquer coisa nos avisa aqui!

**Comment by cali0p3** [comment]
Bom dia!

Muitooo obrigada!

Deu certo. Desculpa a ignorância rsrsrsrsrs

**Comment by eneri-jr** [comment]
Que bom!!!

Nada de ignorância, estamos aqui para aprender juntos!!
Ainda vamos apanhar muito de erros no compilador!! Hehehehehe
