### ISSUE TITLE
Backlog do Mercadin

### ISSUE THREAD

**Issue by jmfantin2** [jmfantin2/ftbok#12]
nos próximos sábados teremos `coding dojos` envolvendo melhorias para o Mercadin (como algumas comentadas no próprio encontro que tivemos). comentem aqui funcionalidades que seriam legais de implementar, e no início dos nossos encontros elencaremos algumas delas para estimar a dificuldade e tentar construir juntos :)

**Comment by g-asantos** [comment]
Essa ideia parece dificil, mas vamo lá:
E se, o Mercadin tivesse tipo um programa de fidelidade? Uma das opções ao entrar seria Entrar no programa de fidelidade, e dali pra frente 10% do valor gastado no Mercadin seria convertido em Mercadindins, que tu poderia trocar por premios.

**Comment by g-asantos** [comment]
Ao terminar a compra, ele pode pedir se você gostaria de colocar cpf na nota, e talvez imprimir uma "nota fiscal" no terminal?

**Comment by jmfantin2** [comment]
Gosto da ideia - não tanto pela implementação, mas pelo exercício de a gente pensar em formas de simplificar esse Épico em User Stories. Vai ser um bom exercício pra mostrar que só se constrói uma feature depois de entender a melhoria que ela propõe para o negócio ;)

https://www.youtube.com/watch?v=MpNVGkI2RD4

**Comment by mayrazan** [comment]
Estava pensando, seria possível adicionar um estoque para os produtos? Aí quando fosse realizar a compra verificaria se aquele produto tem estoque.

**Comment by cali0p3** [comment]
Acredito que já esteja no projeto criar o cadastro dos clientes, e com o cadastro ofertar que ele realize a mesma compra dos produtos que adquiriu anteriormente. Sugerir que a compra seja entregue em seu endereço de cadastro ou em outro endereço.
Criar ações sociais como doação de alimentos.
Criar um campo de pesquisa ou sugestão de produtos não encontrados.

**Comment by g-asantos** [comment]
Acho interessante também colocar algum tipo de validação, quanto aos dados que o usuário coloca. No momento é possível colocar numeros quando é pedido o nome do produto, e colocar um String quando pede numeros resultando num erro maluco.

**Comment by nathaliebsl** [comment]
colocar algum tipo de funçao para descontos.. no sentido de possibilitar, por exemplo a adiçao de um desconto na compra de uma quantidade de produtos x. ou simplesmente para facilitar a modificaçao de preço do produto caso o dono do mercadinho faça algum tipo de promoçao.

**Comment by Jozgon** [comment]
A longo prazo pode ser implementado uma ferramenta que compara preços com outros lugares mostrando que nosso mercado sempre é mais barato ou bem mais razoável de se ter seus produtos?

**Comment by jmfantin2** [comment]
Acho que não daria tempo até o fim de fevereiro, mas poderia sim hehe. Provavelmente tem alguma API aí fora (serviço consumido em rede) que faz uma comparação de preços de produtos de mercado.

**Comment by jmfantin2** [comment]
Vou fechar enquanto estivermos focados nas features que já reunimos.
