### ISSUE TITLE
Sobre construtores

### ISSUE THREAD

**Issue by Jozgon** [jmfantin2/ftbok#13]
Por que construtores não tem parâmetros? para mim ainda está confuso enquanto conceito e aplicação.

**Comment by g-asantos** [comment]
Pelo que eu entendi:
Construtores são formas de inicializar um objeto, que pode vir com parametros pré definidos.
Então por exemplo:
```
public class Hello {
   String name;
   Hello(){
      this.name = "BeginnersBook.com";
   }
}
```

Quanto aos parametros, mais tarde no curso o professor faz constructors com parametros(e faz muito mais sentido). Um exemplo q ele mesmo da q claria tudo, é um que ao iniciar um Aluno, no constructor tem parametros tipo nome, já que não faz sentido criar um aluno sem nome, tu força que quando for inicializar tu tenha q colocar um nome.
N sei se fico claro hahahah

**Comment by Jozgon** [comment]
Não ficou tão claro os construtores ainda, mas quanto aos parâmetros, sim. Totalmente!

**Comment by jonathanribs** [comment]
Como o Guilherme disse, o construtor é o que vai estar iniciando o objeto. O construtor realmente não precisa de ter parâmetros, mas pode ter se necessário. 

O construtor é uma "função" que irá rodar assim que o objeto é criado, e ele só vai rodar 1 vez por objeto. 
Por padrão, ao criar um objeto não irá acontecer nada. Mas você pode colocar um Construtor para, ao objeto ser criado (usando o new), ele settar um valor para os atributos (como no exemplo do Guilherme, que ele inicia o atributo "name" com  "BeginnersBook.com"). Também seria possível mostrar uma mensagem por exemplo.

Se coloca parâmetros no construtor quando você quer passar uma informação ao objeto no momento da sua criação. Como no exemplo, ao criar um objeto Aluno, você já informa o nome (neste caso o Construtor teria que ter um parâmetro do tipo String). Neste exemplo, o construtor seria:
```
public Aluno (String nome){
      this.nome = nome;
}
```

No main, você criaria um novo objeto como:

`Aluno a = new Aluno("NomeDoAluno");`

Neste caso, você está criando um objeto Aluno chamado "a", e já está passando o nome deste aluno entre parênteses, que deve ser do tipo String (por isso o nome entre aspas) assim como foi especificado no Construtor.

É a forma que eu consegui explicar kkkk

**Comment by Jozgon** [comment]
Tá, agora eu acho que entendi melhor.

Eu posso pensar no construtor como uma função principal a um programa que quero fazer?

**Comment by jonathanribs** [comment]
O construtor seria uma função de inicialização de algum objeto...

**Comment by Jozgon** [comment]
Certo, entendi, pensei que fosse algo principal, de um projeto
