### ISSUE TITLE
git log - HEAD e branches 

### ISSUE THREAD

**Issue by nathaliebsl** [jmfantin2/ftbok#14]
Pessoal, segue uma dúvida que está me enlouquecendo

ao dar um git log na minha pasta de trabalho agora surgiram esses dois items em vermelho "origin/main" e "origin/eclipse"
conforme mostra a imagem.
<img width="567" alt="Screen Shot 2020-12-14 at 11 36 39 AM" src="https://user-images.githubusercontent.com/75685745/102103964-65993080-3e0c-11eb-9738-0b33124d23f5.png">

eu nao consigo add nenhum arquivo mais pq me dá um erro dizendo:  error: 'eclipse/' does not have a commit checked out

eu ja busquei mil soluções no google mas nao achei nenhuma que fosse me ajudar e/ou fiquei com medo de executar algumas das soluções que achei...

sinceramente, se que fiz algo errado mas nao sei o que fazer para corrigir.

@g-asantos fui aconselhada a te marcar aqui nesse issue pra me ajudar rs.

Obrigada!

**Comment by g-asantos** [comment]
Talvez eu tenha q invocar o @jmfantin2 pra esse hahah.
Mas o meu google rapido me diz que, talvez seja possivel que tu tenha criado um branch e dai inicializado o git denovo dentro dele? O google me diz que é um erro que pode acontecer quando tu já tem um repositorio e dai tu cria/clona um subdiretorio dentro desse repositorio.
Normalmente agente só vai ter um .git dentro de um projeto q agente tá fazendo.

**Comment by g-asantos** [comment]
Ou,
Talvez tu tento fazer "git add eclipse/*" (no caso de adicionar todos da pasta eclipse)

**Comment by jmfantin2** [comment]
Clonar direto no `eclipse-workspace` pode ser meio fria, dependendo da situação. (talvez não rolasse tudo isso indo na opção Open Project e selecionando outra pasta qualquer de um projeto criado/clonado)

A sugestão:
1. Criar uma pasta `Development` do lado de Desktop e Downloads, com `mkdir Development` no Terminal.
2. Clonar repositórios sempre nessa pasta, e abrir no Eclipse através do comando open mesmo, sempre que necessário.
3. Começar a usar o VSCode como IDE, que vai te facilitar a vida no médio prazo.

Instrução inicial pro item 3: ver se o teu Java tá em versão 11 ou maior, com o comando `java --version` no Terminal. 
Se for o caso, é só instalar o VSCode e clicar nos links das extensões [desse artigo](https://medium.com/@vinicius.b.martinez/microsoft-vscode-para-desenvolvedores-java-f1e9f69e6fa6).
