### ISSUE TITLE
O que seriam as más praticas?

### ISSUE THREAD

**Issue by Jozgon** [jmfantin2/ftbok#17]
Oi, pessoal, tudo bem com vocês?

Fiquei pensando que durante as aulas de alura eles não dizem tanto o que seriam más praticas de hora de codar, independente da linguagem, e queria saber de vocês o que vocês já sabem que é uma má pratica e como detectar uma. Às vezes olho exemplos e exercícios e não consigo dizer que isso ou aquilo está mal feito "contando que funcione", o que poderia ser tão ruim? o que vocês poderiam dizer sobre?

**Comment by g-asantos** [comment]
Que pergunta dificil hahahah. Acho que é muito subjetivo, por exemplo, nas aulas de Java aprendemos varias tecnicas de "reaproveitamento de código", que seria uma boa pratica para evitar repetição de código, mas eu mesmo me questiono se as vezes o código acaba por ficar muito mais dificil de ler e nem sempre pode valer a pena.

Acho que manter uma certo nivel de legibilidade é uma boa pratica facil de entender, principalmente se um dia tu não vai mais trabalhar naquele código e outra pessoa vai precisar manter ele.
Exemplo (com JS):

Eu podia fazer assim:

var Produtos = ["Cheetos, "Doritos"]
var Usuario = "Joanna"

produzirNotaFiscal(Usuario, Produtos) -> Assumindo que essa função já existe

OU

var x = ["Cheetos, "Doritos"]
var y = "Joanna"

funcThree(y, x)


// Moral da historia
@jmfantin2 provavelmente consegue explicar melhor hahah


EDIT: Exemplo que lembrei na cabeça agora que também é evidente:
É uma boa pratica criptografar senhas de usuários antes de coloca-las no banco de dados. Essa também é clara,
mas mais relacionada a questão de segurança.

**Comment by jmfantin2** [comment]
**Excelente** questionamento. Vocês tão voando. 

Quero responder isso melhor outra hora. Por enquanto, dêem um Google em "Princípios SOLID" ;)

**Comment by jmfantin2** [comment]
As boas práticas têm tudo a ver com o território dos Design Patterns e Arquitetura de Software. Essas coisas vão fazer mais sentido assim que entrarmos em frameworks, como o Spring do Java e o React do JS. (o `Código Limpo, do Robert Martin`, e o `Padrões de Projeto, do Eric Gamma` são algumas das bibliografias mais atemporais na área) 

Por agora, vou falar de um exemplo que um professor deu e nunca me esqueci, que era o da "Classe Bacalhau":

> "Suponha que você está criando uma classe para validar entradas de CPF em uma aplicação. Passa-se uma semana e você decide aproveitar uma das funções para validar determinados tokens de transferências bancárias também. Passa-se mais um mês e, por alguma razão, agora há como gerar sorteios da Mega-Sena alí dentro também. Você construiu uma Classe Bacalhau."

Voltando pro SOLID, isso tá claramente infringindo o S, de _Single-responsibility_. O cuidado com as boas práticas faz sentido quando se percebe que o código que você está escrevendo será **legado** para as seguintes situações:

i. você mesmo o revisita em outros pontos no futuro (e a gente esquece da própria linha de raciocínio - é real);
ii. outras pessoas em uma equipe vão manter o projeto ao longo do tempo.

Por essas razões, o código deve se apoiar nesses conceitos e resultar num legado menos confuso (mas é claro que a gente não acerta sempre - o que importa é fazer bonito o suficiente). 

> "O código que eu escrevi nesse exato momento já é legado."

**Comment by damaresmaris** [comment]
Jo ao meu ver , não existe código ruim , mas sim código não testado, código independente da linguagem tem que ser muito testado, milhares de vezes e isso naturalmente vai deixando o aspecto do mesmo mais bonito e estruturado. Código bonito , robusto e estruturado com certeza foi repassado, testado , testado e mais testado. Mesmo para nós iniciantes existem várias formas  de procurarmos formas mais ágeis para codar e testar, institivamente você já cria um código que seja lindo aos olhos e mente de outros programadores. ( Ponto de vista meu tá) e obrigada pela pergunta , ótimo posicionamento.

**Comment by Jozgon** [comment]
No curso de javascript eu tô vendo que uma má prática seria reproduzir a mesma linha de código para uma coisa que deveria ser enxuta, mas eu vejo também que para fazer uma codagem enxuta você precisa de prática, daí fico pensando o quanto quem começa, quem é junior, deveria já saber resumir códigos ou não.

Talvez não haja regras, mas talvez haja algum padrão do que "já deveria ser de praxe".

Sabe?

**Comment by damaresmaris** [comment]
Entendi sim Joanna, uma regra exata que seja dada como padrão acredito que não haja , mas existe o jeito ágil de codar que seria , a forma enxuta que você citou. Ai que entra a autoaprendizagem , na programação nós aprendemos a aprender, e temos que buscar o jeito de programar que mais encaixa em nossa personalidade, sendo ele uma boa prática claro. Não há jeito certo ou errado há jeitos diferentes de solucionarmos problemas e codifica-los.  Mas entendi sua dúvida Jo , acredito que alguém irá postar uma resposta mais esclarecedora para voce. 👍🏻

**Comment by audreybehenck** [comment]
Oiee

Jo, em termos técnicos, acredito que eu ainda não tenha experiência suficiente para efetuar critica e falar que o codigo ta com má prática.
Quando se trata de más práticas, tento sempre focar no que seria uma boa prática, e pensar que o contrario daquilo, é uma má prática.
Por exemplo, aprendemos que o nome da variável deve fazer sentido, então seria uma má prática colocar uma variável como banana kkkk ( a nao ser que teu programa fale de bananas kkkk)
Boas práticas vão além de somente a execução do codigo, precisamos cuidar da legibilidade do que escrevemos (pensar: sera que se outro progamador pegar meu codigo ele vai entender?), identação e principalmente TESTAR tudo que fazemos antes de dar como pronto! 
Até pq, quando trabalhamos em equipe, um código quebrado pode atrapalhar o andamento do projeto.

**Comment by jmfantin2** [comment]
É isso aí gurias. Tudo nessa área respeita uma balança. ⚖️ (lembrem-se disso)

Código enxuto é código menos extenso, mas pra quem tá começando também é menos legível. Aí a gente começa a entrar na zona do "arbitrário" - depende do estilo de quem tá fazendo e de quem vai ler.

```
let msg;

if (contaPaga) {
  msg = 'Tudo certo :)';
} else {
  msg = 'Pague a conta';
}
```

`const msg = { contaPaga ? 'Tudo certo :)' : 'Pague a conta' }`

(acho que esse ternário funciona - esses dois códigos fazem a mesma coisa na prática)

**Resumindo, vocês não são obrigad@s a saber ler/escrever código "esperto" cedo assim. Isso vem com o tempo, realmente. Nesse aspecto, não tenham medo de abraçar o estilo que mais contribui para o entendimento de vocês sobre programação ;)** 

> Apenas atentem aos princípios básicos. Exemplo: repetir determinado trecho de código em vários lugares do projeto costuma ser uma pista de que deveria haver uma classe ou função que faça isso de maneira dinâmica, em um lugar específico. 

Fundamento sempre vence sofisticação. Não tenham pressa para serem sofisticad@s.
