### ISSUE TITLE
O que são programas, softwares e sistemas?

### ISSUE THREAD

**Issue by jmfantin2** [jmfantin2/ftbok#18]
Sabemos o que são algoritmos, mas como essa coisa escala?

**Comment by g-asantos** [comment]
Programas: Conjunto de Instruções ditando a um computador o que fazer.

Software: Conjunto de Instruções + Estruturas de dados que permitam que os programas manipulem corretamente as informações + documentação que descreva suas operações e usos

Sistema: Conjunto de componentes(vários programas/softwares) inter-ligados que funcionam juntos para atingir certo objetivo.  Ex: Sistema Operacional, Sistema Bancário, Sistema Elétrico

**Comment by jmfantin2** [comment]
Exato. O que estamos fazendo até o dia 7 são programas, e depois disso entraremos no território do software. 

Apertem os cintos!
