### ISSUE TITLE
One on ones

### ISSUE THREAD

**Issue by mayrazan** [jmfantin2/ftbok#2]
As one on ones vão ser todos os dias? Como vai funcionar?

**Comment by g-asantos** [comment]
Acredito que seja semanalmente? Minha memoria me falha as vezes, mas certeza que o @jmfantin2 vai te responder rapidinho.

**Comment by jmfantin2** [comment]
Essas conversas com profundidade (que definem as One-on-Ones) a gente vai provavelmente ter 1x/mês.
E vão seguir o padrão mais profissional, menos improvisado, já que terão coletado experiências até a próxima.

https://qulture.rocks/blog/como-fazer-uma-one-on-one-e-por-que/
