### ISSUE TITLE
New Dynamic Web Project - Provider "jar" not found

### ISSUE THREAD

**Issue by jmfantin2** [jmfantin2/ftbok#24]
![image](https://user-images.githubusercontent.com/11260509/104359620-a5783400-54ee-11eb-891a-e5e63fe6606a.png)

postando aqui pra ver se aconteceu com um de vcs, enquanto vou atrás

**Comment by jmfantin2** [comment]
https://stackoverflow.com/questions/15641849/tools-jar-does-not-exist-eclipse-java

vou tentar isso aqui

**Comment by g-asantos** [comment]
Eu encontrei varios problemas pra fazer eclipse funcionar, esse era um deles 
Eu fiz tantas coisas que eu nem lembro exatamente oque deu certo mas o que esse stackoverflow diz foi um deles. Outro era modificar o eclipse.ini pra apontar pro jre direitinho, deve ter algo no google sobre isso.

**Comment by jmfantin2** [comment]
No fim não tá quebrando nada mesmo assim. I'll just ignore it.

**Comment by jmfantin2** [comment]
Na real eventualmente deu ruim federal mesmo. Acabei partindo pra grosseria.

- Desinstalei tudo de Java
- Desinstalei o Eclipse (era o 2020.03)
- Voltei pro vscode pra ver a reclamação dele e instalei a JDK sugerida pelas extensions (que por alguma razão sai mais consistente que as da oracle)
- Instalei o Eclipse Proton (2018), porque essa m#$&@ nem mudou desde lá mesmo.
- Tudo de boa agora
