### ISSUE TITLE
[backend] servlet e objetos

### ISSUE THREAD

**Issue by Jozgon** [jmfantin2/ftbok#25]
Por que um servlet é um objeto?

**Comment by jmfantin2** [comment]
A resposta curta: porque os Servlets coletam uma série de parâmetros na criação e são chamados em várias situações de uma aplicação pra realizar operações e manipular variáveis em tempo de execução.

A resposta longa: https://docs.oracle.com/cd/B14099_19/web.1012/b14017/overview.htm#i1001676

**Comment by Jozgon** [comment]
Entendi demais!
