### ISSUE TITLE
Git usando Terminal do MacOS (.DS_Store)

### ISSUE THREAD

**Issue by nathaliebsl** [jmfantin2/ftbok#4]
Não sei se mais alguém tem/teve esse problema (li na internet ele só afeta usuarios de MacOs? posso estar errada rs)

o "arquivo" .DS_Store está exercitando a minha paciência ao fazer qualquer movimentação pull/push entre pastas e o servidor.... 

Isso é um problema que será sempre recorrente? eu já add o .DS_Store no .gitignore, add esse comando "git rm --cached .DS_Store" também para excluir o arquivo da pasta.. mas tenho a impressão que sempre fica um rabo solto. Enfim, não encontrei a solução definitiva pra esse probleminha... 

alguém tem alguma dica?

**Comment by eneri-jr** [comment]
Boa tarde Nathalie, pelo que andei lendo pode ter vários arquivos deste em seu projeto.
Derrepente da uma olhada nesse site que explica como remover todos esses arquivos do projeto e ainda ensina a fazer um gitignore global para você não se preocupar mais com isso:

https://code.likeagirl.io/how-to-get-rid-of-ds-store-and-node-modules-in-git-repositories-d37b8a391247?gi=f7826370f756

**Comment by jmfantin2** [comment]
Tô com o Júnior. Parece certo. (só é importante saber que tudo que tem `global` se aplica a todos os diretórios da máquina)
Se for no projeto de Git, não esquenta muito não, que vocês vão aprender muito mais na prática do que no curso da Alura.

Por mim tu já pula pra Java e aguarda melhores explicações no sábado.

#Incentivo: até [nesse calhamaço de projeto](https://github.com/jmfantin2/rn_negocio_direto) tudo que eu precisei foram os comandos básicos, então vamos por partes ;)

**Comment by nathaliebsl** [comment]
"Por mim tu já pula pra Java e aguarda melhores explicações no sábado."

era tudo que eu queria ouvir hahaha

Obrigada pessoal!
