### ISSUE TITLE
O que vocês estão entendendo do git até agora?

### ISSUE THREAD

**Issue by jmfantin2** [jmfantin2/ftbok#5]
adoro respostas erradas que vêm do coração

**Comment by damaresmaris** [comment]
Ele é muito importante para desenvolvedores,  ele nos ajuda com as versões dos arquivos, através deles podemos desenvolver projetos e também não subescreve as outras versões.

**Comment by vicorotto** [comment]
Ele é extremamente importante para desenvolvimento em times

**Comment by jmfantin2** [comment]
Já fiz trabalho da faculdade sobrescrevendo arquivo em pen drive. E também já versionei pelo google drive pra poder compartilhar. Deu ruim mais vezes do que dá pra contar nos dedos.

**Comment by nathaliebsl** [comment]
estou em águas rasas ainda, mas conceitualmente entendo que o git é uma ferramenta que facilita o compartilhamento e atualização de informações/dados para times de desenvolvedores que trabalham em um mesmo projeto.

**Comment by eneri-jr** [comment]
Um sistema de controle de versões, muito utilizado em desenvolvimento de softwares e que abrange várias funcionalidades que ajudam no controle de versionamento por exemplo mostrar edições que foram feitas em cada arquivo comitado.

**Comment by jonathanribs** [comment]
Uma ferramenta que facilita o trabalho de programação quando mais de uma pessoa tem que trabalhar no mesmo projeto. Ele evita que alguma atualização feita por alguém se perca além de permitir ter o controle das versões anteriores. De modo geral ajuda a ter um controle sobre o que está sendo feito.

**Comment by audreybehenck** [comment]
É  uma ferramenta muito importante pra desenvolvimento em equipe.
O Git serve, por exemplo, para todos os membros da equipe salvarem seus códigos, onde todos terão acesso, facilitando assim o controle sobre o que esta sendo feito com o projeto. 
Muito provavelmente, durante o desenvolvimento do projeto, você fará várias alterações no código e isso pode implicar no desenvolvimento dos códigos das outras pessoas da equipe. Então com Git, seus colegas de equipe serão informados a cada atualização do seu código, facilitando assim o trabalho deles em ver os ajustes nos códigos deles e também ver se esta tudo funcionando corretamente.
Além de facilitar, também acho que deixa tudo mais organizado.
