### ISSUE TITLE
Como compilar java no linux?

### ISSUE THREAD

**Issue by Jozgon** [jmfantin2/ftbok#6]
Na lição 10 da aula 2 de introdução a java, como eu compilo? existe o passo 5 que é "Agora, compile o código utilizando o compilador de Java da Oracle, chamado de javac" como faço isso? esse compilador vem junto com java que instalo?

**Comment by jmfantin2** [comment]
Maneira fácil de ver se a máquina entende é só digitar `javac` e ver o que acontece. Quando diz "comando desconhecido", é porque não tem nenhum programa na máquina com a alias (nesse caso javac) cadastrada.

Acredito que já esteja lá sim.

**Comment by jmfantin2** [comment]
Senão, tem que fazer algo parecido com isso.
https://beginnersbook.com/2013/05/first-java-program/

`javac classname.java` → gera o .class → `java classname`

**Comment by Jozgon** [comment]
Isso eu faço no terminal?

**Comment by jmfantin2** [comment]
aham. acho que se tu botar `java --help` ou algo parecido ele vai te dizer se reconhece já

**Comment by Jozgon** [comment]
Eu vou tentar.

**Comment by Jozgon** [comment]
Olá, eu acredito que tive sucesso ao usar o VsCode, porém acho estranho ele não ser como o CODE::BLOCKS IDE que geralmente mostra uma tela preta pequena como um prompt de comando mostrando a mensagem "olá mundo", também acho que falta instalar alguma coisa para codar pelo terminal. Queria ter a certeza de que posso testar trabalhos em mais de uma forma.

**Comment by jmfantin2** [comment]
Acho que isso do CodeBlocks é um terminal integrado. Lá no menu do vscode dá pra deixar um terminal prontinho embaixo do editor ;)
