### ISSUE TITLE
Exercicios, Projetos durante o flowtalents

### ISSUE THREAD

**Issue by g-asantos** [jmfantin2/ftbok#7]
Como esse repositório foi colocado no privado, eu fiquei com essa dúvida.
Existe problema em colocar, por exemplo, os exercicios que eu to fazendo de Java no alura em um repositório do github?
E projetos desenvolvidos durante o flowtalents?

**Comment by jmfantin2** [comment]
Excelente pergunta!

R: Não tem problema :)

R+: E pelo amor de deus, pelo sucesso de vocês, **recheiem seus perfis com os repositórios dos cursos e exercícios!** O portfólio de projetos é a evidência mais rica do desenvolvimento de vcs na área. (o FTBOK só que tem que ficar no privado porque a gente tá aplicando um método muuuuito foda aqui dentro, e isso é estratégico)
