### ISSUE TITLE
Instalação JDK

### ISSUE THREAD

**Issue by cali0p3** [jmfantin2/ftbok#8]
Mesmo seguindo o passo a passo da instalação, só consegui localizar o JRE.

Alguém me da um help?

**Comment by eneri-jr** [comment]
Bom dia,

Este artigo te mostra como fazer as instalações do JRE e do JDK e mais pro final eles te ensinam para saber se o compilador do Java está instalado corretamente:

https://medium.com/@mauriciogeneroso/configurando-java-1-instala%C3%A7%C3%A3o-do-jre-e-do-jdk-no-windows-38cacace0377

**Comment by cali0p3** [comment]
Bom dia :)
Obrigada.

Ainda não consegui encontrar ou identificar se houve algum erro.
Existe a possibilidade de ter instalado apenas o jre?

**Comment by eneri-jr** [comment]
Sim.
Se tu baixou o pacote de instalação somente do JRE, ai sim. Este seria para quem somente quer usar aplicações do Java em seu pc.
Para nós desenvolvedores precisamos do pacote de desenvovilmento do Java que é o JDK que tem dentro dele o JRE.

**Comment by jonathanribs** [comment]
Em Arquivos de Programa, na pasta Java, tem que ter duas pastas, a do JRE e a do JDK. Se não tiver a pasta JDK deve ter havido algum erro na instalação, ou você pode ter alterado o diretório na hora de instalar e por isso não está achando. Confere isso

**Comment by cali0p3** [comment]
Então, o problema é este.
Instalei o jdk-8u271-windows-x64.

E mesmo assim na pasta esta apenas o jre1.8.0_201

**Comment by cali0p3** [comment]
Durante a instalação segui o passo-a-passo, só dei next.

**Comment by cali0p3** [comment]
Vou desinstalar e instalar de novo, então.

**Comment by jmfantin2** [comment]
Vou repetir os passos aqui também e aviso o que fiz para dar certo

**Comment by cali0p3** [comment]
Resolvido. Acredito que com  reinstalação deu tudo certo.
Obrigada.

**Comment by jmfantin2** [comment]
Aeee!
AQUI NÃO HAHAHAHAH

**Comment by jmfantin2** [comment]
Parabéns Oracle por ser uma organização tão engessada. Os caras seguem no ano 2000.
Enfim. Vou fechar essa issue só depois que eu fizer um report básico do que eu tive que fazer no meu caso.

**Comment by cali0p3** [comment]
Beleza, vou seguir os próximos passos e ver se realmente esta tudo ok.

**Comment by jmfantin2** [comment]
Pra rodar aqui:

JRE 8: jre-8u271-windows-i586.exe
JDK 11: jdk-11.0.9_windows-x64_bin.exe (vscode tem que ser 11+)

coloquei os installers no [google drive](https://drive.google.com/drive/folders/1fffazAHZbi7phEGDc-kGHtGji2swl9Hf?usp=sharing) porque na oracle tende a ser meio confuso de achar. o problema é que deve demorar horrores pra baixar a jdk por aí.

E o que faltava pra mim era ir nas `environment variables` e adicionar `JAVA_HOME` pro caminho da jdk em questão. Acho que colocar entre as User vars já basta, mas é bom em System também, por via das dúvidas.

![image](https://user-images.githubusercontent.com/11260509/101787322-b859ac00-3add-11eb-907e-e24d24e417b5.png)

**Comment by cali0p3** [comment]
Aqui fluiu normal.

Acredito que o problem era eu.. rsrsrsrs

**Comment by jmfantin2** [comment]
Vivi o suficiente pra dizer que **a Informática não é uma ciência exata**. Nunca vou me esquecer de ter visto dois computadores da mesma empresa, zerados, rodarem o mesmo programa e um quebrar e outro não. 

O universo apronta umas com a gente. A regra é não se desesperar kkk
