### ISSUE TITLE
module-info.java?

### ISSUE THREAD

**Issue by Jozgon** [jmfantin2/ftbok#9]
No eclipse ao fazer o meu "olá mundo", tive problema de compilação, eu recebia na linha 1 a mensagem "must declare a named package because this compilation unit is associated to the named module 'program'" mas me auxiliaram a tirar o "arquivo" (eu acho) "module-info.java". Feito isso, pude compilar meu "olá mundo".

Por que isso?

**Comment by jmfantin2** [comment]
pelo que eu saiba, ter uma package declarada serve pra evitar que duas classes com o mesmo nome (que fazem coisas diferentes) sejam confundidas. 

isso passa a fazer sentido quando se mexe em projetos gigantescos - uma vez dei manutenção num projeto com váááários módulos que se comunicavam, e a tendência é que certos termos comuns, como `RequestController` se repitam.

importando a package `messages` no arquivo que instanciava uma RequestController, tínhamos garantia que estávamos tratando requests de mensagem, e não de criação de anúncio, por exemplo. isso foi em Angular.js, mas a ideia é a mesma ;)

**Comment by Jozgon** [comment]
Então eu fiz errado em remover o arquivo?

**Comment by jmfantin2** [comment]
não ;)

o que importa aqui é sempre resolver o problema da maneira mais simples possível. as coisas ficam naturais com o tempo, então quando chegar a hora de mexer com módulos, outras soluções simples vão surgir.

_as aplicações mais complexas e utilizadas do mundo foram construídas um passo de cada vez_.

**Comment by Jozgon** [comment]
Certo! entendi!
